Updated URLs. Other tidying.
gridcoin-community/Gridcoin-Research pull request #1315
Opened 2018-10-08 07:55 UTC by Peppernrino

Added link to BOINC site.
SSL'd main site.
Updated Tags URL.
Removed duplicate sentence.
Grammar.
Capitalized Freenode and IRC.
Updated IRC channel to #gridcoin-help, as it is the help channel and you have to be a registered user to use #gridcoin.
SSL'd Slack URL.
Fixed header line markdown.
Removed unnecessary spaces.

2018-10-08 19:33 UTC, barton2526 commented on README.md
> -are created regularly to indicate new official, stable release versions
Why is this segment removed?

2018-10-10 08:25 UTC, tomasbrod requested changes

2018-10-14 02:16 UTC, Peppernrino commented on README.md
>  worked on by several people.
I'm sorry you don't like how it looks in code, but of course it works! lol why would I submit something that doesn't work? :D 

I'm not sure what you mean by the semantic of branches... I only changed the URL to point to the community repo.

2018-10-14 02:16 UTC, Peppernrino commented
I'm sorry you don't like how it looks in code, but of course it works! lol why would I submit something that doesn't work? :D

I'm not sure what you mean by the semantic of branches... I only changed the URL to point to the community repo.

2018-10-19 18:04 UTC, tomasbrod requested changes
- I retract my comment about branch semantics. You only changed URLs.
- However I stand by the dashes&equals. Please undo the regression. Markdown is a format that should look good both in source and when rendered. Onle lone equal sign under heading looks wrong. 
- I am not hating your work.

2018-10-22 17:19 UTC, Peppernrino commented
updated in #1337 :)

2018-10-22 17:19 UTC, closed without merging