Reduce GCC6/C++11 warnings and use distro LevelDB.
gridcoin-community/Gridcoin-Research pull request #162
Opened 2016-12-03 18:59 UTC by Techbert08

I was troubleshooting a build problem and ended up fixing a lot of small C++11 issues and GCC6 warnings along the way.  I can cut this into pieces if you only want part of it.

1. Updated build instructions and Unix Makefile to use the distro's LevelDB.  This works on Ubuntu 16.04LTS.
2. Switched auto_ptr to boost:shared_ptr because the former is deprecated in C++11.
3. Got rid of unused variables and functions caught by GCC.
4. Eliminated all -Wmisleading-indentation warnings with the exception of cpid.cpp. This highlighted the very different tab/space styles throughout the code, but I attempted to match the style of the immediate context.  cpid.cpp looks like it needs an autoformatter.
5. Fixed -Wliteral-suffix warnings around the 64-bit printfs so it will work with C++11.

After doing this I noticed that my editor had made line endings consistent in main.cpp.  They were previously a mix of Windows and Unix, which confused the Git diffs.  I think the files are correct, but the diff view is funny.

My editor also stripped trailing whitespace, but I couldn't filter it because of point 5 above.  On one hand I like the improved consistency, but it makes this change unwieldy.

2016-12-03 19:04 UTC, denravonska commented
May I suggest using std::shared_ptr instead? I don't know of any compiler, except maybe some obscure Windows CE compiler, that doesn't support it anymore.

Kudos on the line ending fix. It has been a recurring annoyance for me.

In the long run I would also like to replace all the long iterator constructs (`std::map<onetype, anothertype>::iterator mi`) with `auto`, but that's another show.

2016-12-03 21:29 UTC, Techbert08 commented
See what you think.  I had to update the compiler flags to add -std=c++11, and I suspect something similar will be required on the others.  Autotools or some other build system might be helpful for getting the different build targets in gear.

2016-12-04 07:48 UTC, denravonska requested changes
For minor improvements in allocation speed and reduced memory fragmentation you can change `std::shared_ptr<CBlock> pblock(new CBlock());` to `std::shared_ptr<CBlock> pblock = std::make_shared<CBlock>();`. This combines the allocation of the object storage and the reference counter into one memory block instead of two.

2016-12-04 14:23 UTC, Techbert08 commented
That makes sense, though on second thought if upgrading to C++11 anyway this should be a unique_ptr to avoid reference counting at all.  I think that upgrading is worth doing, but there will need to be a swing through the Qt code to make sure it compiles correctly, and I'd want to check on Windows, too.  I'll see what @gridcoin says, but I think it would be easier to go back to the Boost pointer in this PR, separately update the build to C++11 (or even C++14), then then start using the new features.

2016-12-04 16:24 UTC, denravonska commented
Yeah, we could use `unique_ptr` but I find it to be very cumbersome to use since you cannot copy it and have to use its move semantics when returning it. The `boost::shared_ptr` is also referenced counted but if we want the same semantics without the overhead we could use `boost::scoped_ptr`. However, I think the RAM overhead is fairly negligible and the runtime overhead should be none when we pass references around. Compare to how often variables (std::string, mostly) are passed by value instead of by reference.

2016-12-08 11:41 UTC, Evisceration commented
@Techbert08 i guess you missed something to really use the distro leveldb


distro-leveldb.patch

```
commit c0501afbb886235c9b71c4ea58092b604b15ea2c
Author: Alexander Martinz <eviscerationls@gmail.com>
Date:   Thu Dec 8 12:37:14 2016 +0100

    really use distro leveldb
    
    Signed-off-by: Alexander Martinz <eviscerationls@gmail.com>

diff --git a/gridcoinresearch.pro b/gridcoinresearch.pro
index 9d87e03..ce84f68 100644
--- a/gridcoinresearch.pro
+++ b/gridcoinresearch.pro
@@ -117,26 +117,27 @@ contains(NO_UPGRADE, 1) {
     DEFINES += NO_UPGRADE
 }
 
-INCLUDEPATH += src/leveldb/include src/leveldb/helpers
-LIBS += $$PWD/src/leveldb/libleveldb.a $$PWD/src/leveldb/libmemenv.a
-SOURCES += src/txdb-leveldb.cpp
 !win32 {
-    # we use QMAKE_CXXFLAGS_RELEASE even without RELEASE=1 because we use RELEASE to indicate linking preferences not -O preferences
-    genleveldb.commands = cd $$PWD/src/leveldb && CC=$$QMAKE_CC CXX=$$QMAKE_CXX $(MAKE) OPT=\"$$QMAKE_CXXFLAGS $$QMAKE_CXXFLAGS_RELEASE\" libleveldb.a libmemenv.a
+    LIBS += -lleveldb -lmemenv
 } else {
+    INCLUDEPATH += src/leveldb/include src/leveldb/helpers
+    LIBS += $$PWD/src/leveldb/libleveldb.a $$PWD/src/leveldb/libmemenv.a
+    SOURCES += src/txdb-leveldb.cpp
+
     # make an educated guess about what the ranlib command is called
     isEmpty(QMAKE_RANLIB) {
         QMAKE_RANLIB = $$replace(QMAKE_STRIP, strip, ranlib)
     }
     LIBS += -lshlwapi
     genleveldb.commands = cd $$PWD/src/leveldb && CC=$$QMAKE_CC CXX=$$QMAKE_CXX TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) OPT=\"$$QMAKE_CXXFLAGS $$QMAKE_CXXFLAGS_RELEASE\" libleveldb.a libmemenv.a && $$QMAKE_RANLIB $$PWD/src/leveldb/libleveldb.a && $$QMAKE_RANLIB $$PWD/src/leveldb/libmemenv.a
+
+    genleveldb.target = $$PWD/src/leveldb/libleveldb.a
+    genleveldb.depends = FORCE
+    PRE_TARGETDEPS += $$PWD/src/leveldb/libleveldb.a
+    QMAKE_EXTRA_TARGETS += genleveldb
+    # Gross ugly hack that depends on qmake internals, unfortunately there is no other way to do it.
+    QMAKE_CLEAN += $$PWD/src/leveldb/libleveldb.a; cd $$PWD/src/leveldb ; $(MAKE) clean
 }
-genleveldb.target = $$PWD/src/leveldb/libleveldb.a
-genleveldb.depends = FORCE
-PRE_TARGETDEPS += $$PWD/src/leveldb/libleveldb.a
-QMAKE_EXTRA_TARGETS += genleveldb
-# Gross ugly hack that depends on qmake internals, unfortunately there is no other way to do it.
-QMAKE_CLEAN += $$PWD/src/leveldb/libleveldb.a; cd $$PWD/src/leveldb ; $(MAKE) clean
 
 # regenerate src/build.h
 !windows|contains(USE_BUILD_INFO, 1) {
```

this should use the system's leveldb on everything except windows.

2016-12-25 08:07 UTC, denravonska commented
What's the status of this PR?

2016-12-26 21:51 UTC, Techbert08 commented
With the holidays it got stuck for a while.  I'm around, and I can keep iterating or close, depending on what you want to do.

2016-12-27 07:24 UTC, denravonska commented
I meant ftom the repo owner :D
I want this merged as well since it makes my life easier.

2017-01-03 06:30 UTC, denravonska commented
Sorry to be a nag but can we please merge this after the new conflicts have been resolved? It's getting silly having to use two editors :)

2017-01-30 15:13 UTC, denravonska commented
Would you mind adapting this PR to the most recent code and submitting it to @gridcoin-community/Gridcoin-Research? Though I think we should stick with the supplied leveldb so always use a known version.

2017-02-18 18:17 UTC, denravonska commented
I'm not sure we should use the distro's db. I tried upgrading it in a local branch and the block chain would no longer pass the assertion test after loading. libdb does need to be updated but I think we have to have some control over when that happens.

2017-02-18 18:35 UTC, Evisceration commented
Then i would rather ship external code as submodules and enforce its usage.
Right now it is a bit of a mess, eg it uses distro's openssl, which on recent distros like Fedora breaks the build.

2017-02-18 18:53 UTC, denravonska commented
I agree. I'll think a bit about the dependencies. Bitcoin still ships leveldb with their source so I guess there's a good reason for it.

Regarding OpenSSL I still need help testing my fix in #185. I'm running it on my wallet but that's with OpenSSL 1.0.2.

2017-02-19 08:52 UTC, denravonska commented
Can we resolve this in favor of #174 which is now in the development branch?

2017-02-19 20:33 UTC, Techbert08 commented
That seems reasonable to me.  It looks like the main bits that were in here to make whitespace more regular were taken care of, and I can see that relying on the platform's levelDB is probably more trouble than it's worth.  I'll close this out.

2017-02-19 20:33 UTC, closed without merging