wallet: Stop Error When Starting From Zero
gridcoin-community/Gridcoin-Research pull request #1759
Opened 2020-06-25 23:09 UTC by RoboticMind

Stops the check from throwing an error if starting from zero. Fixes the bug introduced from #1748

2020-06-25 23:20 UTC, jamescowens requested changes
Let's just use Cycy's abbreviated form... 

if (pindex->pprev && pindexGenesisBlock && pindex != pindexGenesisBlock)

2020-06-25 23:35 UTC, RoboticMind commented
Changed it to that. Personally I like to separate it out to the different parts in how I view the logic, but that other form works.

2020-06-25 23:59 UTC, jamescowens approved these changes

2020-06-25 23:59 UTC, merged

2020-06-26 00:30 UTC, jamescowens commented
This is still wrong. It should be if (pindex->pprev == nullptr && pindexGenesisBlock && pindex != pindexGenesisBlock).

I will just push a commit directly to dev to fix.

2020-06-26 01:03 UTC, RoboticMind commented
Oh oops didn't even notice that the shortened form took out the `== nullptr` part. Probably should have looked at that closer

2020-06-26 02:16 UTC, jamescowens commented
No biggie.