doc: add issue templates for bug reports and feature requests
gridcoin-community/Gridcoin-Research pull request #2147
Opened 2021-05-25 14:45 UTC by Pythonix

I think it would be good if we also use Issue templates to increase the quality of opened Issues. The templates are from https://github.com/dogecoin/dogecoin/commit/b5989ee0386a99dba20f9188384248baa8c4d4d8

2021-05-26 09:09 UTC, nathanielcwm requested changes
I think adding a note to try updating to the latest leisure would be helpful.

2021-05-26 09:09 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA. -->
```suggestion
<!-- List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA. 
If you are not on the latest Leisure release please try updating to that and see if your issue still persists. -->
```

2021-05-26 09:15 UTC, nathanielcwm requested changes
Autolabel issues.

2021-05-26 09:15 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: '[bug] '
```suggestion
title: '[bug] '
labels: bug
```

2021-05-26 09:15 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/feature_request.md
> +title: '[feat] '
```suggestion
title: '[feat] '
labels: enhancement
```

2021-05-27 14:39 UTC, jamescowens commented
How is this actually going to work? I am not sure it is worth the bother unless it shows up automatically when someone presses the new issue button in github.

2021-05-27 15:32 UTC, Pythonix commented
@jamescowens Yes, the templates appear when someone opens an issue. If you open an issue on my fork, you can test it out.

2021-05-27 15:50 UTC, nathanielcwm commented
![image](https://user-images.githubusercontent.com/22572406/119857551-40295a80-bf46-11eb-880a-5a288c8c2556.png)
@jamescowens that's a demo of another project using issue templates.

Actually tbh we should prolly just link to the Discord / Slack / IRC

2021-05-27 15:59 UTC, nathanielcwm commented
@Pythonix you can cherrypick my commit 97e20bfb9681927a297e2a930fc9796deb32a693

2021-05-27 16:01 UTC, nathanielcwm commented
nvm security is already there from the security.md file lol

2021-05-27 17:22 UTC, Pythonix commented
> @Pythonix
> 
> ```yaml
> blank_issues_enabled: true
> contact_links:
>   - name: Gridcoin Discord
>     url: https://discord.gg/jf9XX4a
>     about: Please go here if you have any general issues, that aren't bug reports. We can assist you much faster there.
>   - name: Gridcoin Subreddit
>     url: https://old.reddit.com/r/gridcoin
>     about: Alternative platform.
> ```
> 
> Don't forget to put me as coauthor +1

Should we really enable blank issues? Why not just stick to the templates?

2021-05-27 17:44 UTC, jamescowens requested changes
See my comments.

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Please make sure you are posting an technical issue related to Gridcoin. -->
a not an

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!--  Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application or sample code -->
Let's just leave it at "Please explain the steps required to duplicate the issue." Developers that are code aware will know to include code snippets. I don't necessarily want imply that we require non-programmers to actually do work in the code itself.

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- This is normally the contents of a `debug.log` file. Raw text or a link to a pastebin type site are preferred. -->
"is" preferred, not "are" preferred. When two singular subjects are connected by "or", the verb is singular.

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/feature_request.md
> +title: '[feat] '
Spell out feature.

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- Please make sure you are posting an technical issue related to Gridcoin. -->
Same here.... a, not an.

2021-05-27 17:44 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- A clear and concise description of any alternative solutions or features you've considered. -->
you have. No contractions in formal documentation.

2021-05-27 22:16 UTC, nathanielcwm commented
> Should we really enable blank issues? Why not just stick to the templates?

Ig this can be discussed.

2021-05-27 22:45 UTC, jamescowens commented
If we are going to go to the trouble of templates, we should require their use.

2021-05-28 00:09 UTC, nathanielcwm commented
Just swap the bool then

2021-05-29 21:38 UTC, jamescowens commented
@cyrossignol I would like your POV on this.

2021-06-01 22:45 UTC, cyrossignol reviewed
Seems like good functionality to add. I don't think we get too many invalid tickets right now, but the templates may help if the project's popularity grows.

2021-06-01 22:45 UTC, cyrossignol commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Current behavior:**
Minor: should we be consistent with the colons on the headings?

2021-06-01 22:45 UTC, cyrossignol commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: '[bug] '
Minor: any need to keep the `title` template when we have labels? Seems like noise.

2021-06-01 22:45 UTC, cyrossignol commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://old.reddit.com/r/gridcoin
Is old Reddit ever going away?

2021-06-01 22:45 UTC, cyrossignol commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- Please make sure you are posting a technical issue related to Gridcoin. -->
```suggestion
<!-- Please make sure you are posting a technical feature request related to Gridcoin. --> 
```

2021-06-01 22:45 UTC, cyrossignol commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION. -->
```suggestion
<!-- REQUESTS MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION. -->
```

Not sure if this line is really necessary for feature requests.

2021-06-02 14:04 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* [Gridcoin on reddit](https://www.reddit.com/r/gridcoin/)
Since these are in comments having it be markdown linked seems redundant?

2021-06-02 14:06 UTC, nathanielcwm requested changes

2021-06-02 14:06 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* [Gridcoin on reddit](https://www.reddit.com/r/gridcoin/)
Since these are in comments having it be markdown linked seems redundant?

2021-06-02 14:06 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/feature_request.md
> +* [Gridcoin on reddit](https://www.reddit.com/r/gridcoin/)
Same issue here as above

2021-06-02 14:06 UTC, nathanielcwm commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, et
Might be good to also add smth like `related bitcoin issue` to the list

2021-06-02 14:10 UTC, nathanielcwm commented
Also probably a good idea to put smth in the feature request template about this repo being specifically for the wallet software only & to go to Gridcoin-Tasks, Site etc for other stuff.

2021-06-10 22:07 UTC, jamescowens requested changes
Some more comments as a result of a close review.

2021-06-10 22:07 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please go here if you have any general issues, that aren't bug reports. We can assist you much faster there.
general issues that aren't bug reports (no comma)

2021-06-10 22:07 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- If you are able to illustrate the feature request with an example, please provide a samples via an online code collaborator such as [StackBlitz](https://stackblitz.com), or code snippet on [GitH
provide a sample (no s). Shouldn't we list the native tool (GitHub) first?

2021-06-10 22:07 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, et
relevant to your feature request (not issue)

2021-06-11 13:43 UTC, Pythonix commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, et
Good catch! I also removed the `Stack traces` probably not relevant for a feature request.

2021-06-11 14:49 UTC, jamescowens requested changes
Let's get this last change done and that should be it.

2021-06-11 14:49 UTC, jamescowens commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please go here if you have any general issues that aren't bug reports. We can assist you much faster there.
I didn't see this before. No contractions in formal technical writing. aren't should be are not.

2021-06-11 16:35 UTC, nathanielcwm commented
Does anyone here personally use stackblitz.

Prolly not a great idea to give free advertising to random websites.

2021-06-12 07:00 UTC, Pythonix commented
> stackblitz

I tried them for this PR. But let's just remove it.

2021-06-12 11:36 UTC, nathanielcwm commented
iirc there is another instance on the feature request file?

2021-06-12 11:50 UTC, Pythonix commented
> iirc there is another instance on the bug report file?

Don't think so.

2021-06-12 21:52 UTC, jamescowens approved these changes

2021-06-12 21:52 UTC, merged