Remove travis references
gridcoin-community/Gridcoin-Research pull request #2156
Opened 2021-06-02 20:54 UTC by barton2526

before_install.sh might be able to be removed entirely, see (https://github.com/bitcoin/bitcoin/pull/20691/commits/09d105ef0f8b4b06bf248721a1209c9e16e9db75).

2021-06-02 21:37 UTC, barton2526 commented
@jamescowens if you want this to close #2154 I need to know whether we want to replace the icons or remove them entirely

2021-06-02 22:11 UTC, jamescowens commented
Replace

2021-06-02 22:36 UTC, barton2526 commented
Here's what it looks like with this PR
![image](https://user-images.githubusercontent.com/20938755/120560850-80b72700-c3d1-11eb-98b9-ff276e843844.png)

2021-06-03 11:22 UTC, div72 requested changes
The before_install script contains the folds which are supported in GitHub actions.

2021-06-03 11:22 UTC, div72 commented on ci/lint/06_script.sh
> +if [ "$CI_EVENT_TYPE" = "pull_request" ]; then
```suggestion
if [ "$EVENT_TYPE" = "pull_request" ]; then
```
or (remove the env this env var in the workflow)
```suggestion
if [ "$GITHUB_EVENT_TYPE" = "pull_request" ]; then
```
If you want to preserve the `CI_EVENT_TYPE`, you could edit workflow file to change the env name.

2021-06-03 19:38 UTC, div72 commented on ci/lint/06_script.sh
>  fi
```suggestion
```
Forgot that it's already handled underneath.

2021-06-03 21:39 UTC, barton2526 commented
gonna need to be squashed lol

2021-06-05 13:41 UTC, jamescowens commented
@div72 can you check this one last time and make sure you are satisfied?

2021-06-05 17:33 UTC, div72 approved these changes
@jamescowens I was waiting on barton to squash.

2021-06-05 19:51 UTC, jamescowens commented
I am squashing on merge.

2021-06-05 19:51 UTC, merged