doc: Remove CCT from README and release process docs
gridcoin-community/Gridcoin-Research pull request #2175
Opened 2021-06-12 06:26 UTC by barton2526

it's dead :(

2021-06-12 07:18 UTC, barton2526 commented
Should we add Discord to the README so it doesn't feel empty?

2021-06-12 08:58 UTC, Pythonix commented
> Should we add Discord to the README so it doesn't feel empty?

IMHO yes =)

2021-06-12 14:38 UTC, jamescowens requested changes
Please add Discord.

2021-06-12 19:25 UTC, div72 commented
Freenode link could also be updated to liberachat.

2021-06-12 19:52 UTC, barton2526 commented
> 
> 
> Freenode link could also be updated to liberachat.

The reason I didn't go through with this is because we are currently operating both irc networks.  I'm not sure which has more users.

2021-06-12 20:05 UTC, RoboticMind commented on doc/README.md
>  * You can also join us on [Slack](https://grcinvite.herokuapp.com/) with the invite Token GRCsquad
Should probably switch the slack link to use the link used everywhere else
```suggestion
* You can also join us on [Slack](https://join.slack.com/t/teamgridcoin/shared_invite/enQtMjk2NTI4MzAwMzg0LTE4N2I3ZWZjYWJlZGM1Zjg3MTUyMDhiN2M5NmRmZTA2NDA0ZmY1ZTFmOGM3ZGU2YTBkOTdhNTk2ZjkzMGZkODY/)```

2021-06-12 23:22 UTC, jamescowens commented
Maybe we should put both?

2021-06-13 00:05 UTC, jamescowens approved these changes
ACK

2021-06-13 00:05 UTC, merged

2021-06-13 00:05 UTC, jamescowens commented
We are going to leave as is.