qt: Follow Qt docs when implementing rowCount and columnCount
gridcoin-community/Gridcoin-Research pull request #2333
Opened 2021-09-14 23:24 UTC by barton2526

> [`QAbstractItemModel::rowCount`](https://doc.qt.io/qt-5/qabstractitemmodel.html#rowCount):
> 
> > **Note:** When implementing a table based model, `rowCount()` should return 0 when the parent is valid.
> 
> [`QAbstractItemModel::columnCount`](https://doc.qt.io/qt-5/qabstractitemmodel.html#columnCount):
> 
> > **Note:** When implementing a table based model, `columnCount()` should return 0 when the parent is valid.

Ref: https://github.com/bitcoin-core/gui/pull/173

2021-09-18 15:19 UTC, jamescowens requested changes
Didn't you miss one in bitcoinunits.cpp?

int BitcoinUnits::rowCount(const QModelIndex &parent) const
{
    Q_UNUSED(parent);
    return unitlist.size();
}

2021-09-18 23:06 UTC, barton2526 commented
> 
> 
> Didn't you miss one in bitcoinunits.cpp?
> 
> int BitcoinUnits::rowCount(const QModelIndex &parent) const
> {
> Q_UNUSED(parent);
> return unitlist.size();
> }

@jamescowens is BitcoinUnits implementing a `QAbstractItemModel`? If it is, upstream missed it too...
https://github.com/bitcoin-core/gui/blob/773f8c1a7d568012768e16d2ede65b5d4d62aced/src/qt/bitcoinunits.cpp#L221

2021-09-18 23:08 UTC, jamescowens commented
I didn’t check thoroughly… so my comment may be a false positive.

Sent from my iPhone

> On Sep 18, 2021, at 7:06 PM, barton26 ***@***.***> wrote:
> 
> ﻿
> Didn't you miss one in bitcoinunits.cpp?
> 
> int BitcoinUnits::rowCount(const QModelIndex &parent) const
> {
> Q_UNUSED(parent);
> return unitlist.size();
> }
> 
> @jamescowens is BitcoinUnits implementing a QAbstractItemModel? If it is, upstream missed it too...
> https://github.com/bitcoin-core/gui/blob/773f8c1a7d568012768e16d2ede65b5d4d62aced/src/qt/bitcoinunits.cpp#L221
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-09-18 23:10 UTC, barton2526 commented
It is my understanding that BitcoinUnits.cpp implements a list model

2021-09-18 23:20 UTC, jamescowens commented
Then I retract my comment.

Sent from my iPhone

> On Sep 18, 2021, at 7:10 PM, barton26 ***@***.***> wrote:
> 
> ﻿
> It is my understanding that BitcoinUnits.cpp implements a list model
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-09-19 00:03 UTC, jamescowens approved these changes
utACK

2021-09-19 00:03 UTC, merged