gui: Add text output and dialog boxes for -help and -version in GUI client
gridcoin-community/Gridcoin-Research pull request #2378
Opened 2021-11-07 00:17 UTC by jamescowens

2021-11-07 17:40 UTC, div72 requested changes
There already was some code for help in `StartGridcoinQt`. Could you remove/incorporate that?

2021-11-07 19:32 UTC, jamescowens commented
Ok. That should do it. I implemented a clever horizontalSpacer to make the message box larger (for the detailed info scroll box) because the hacky way with non-breaking spaces was not working properly.

2021-11-07 19:36 UTC, jamescowens commented
I thought it was a good idea for me to fix this, since I essentially broke it when I refactored stuff in here a while back. :)

2021-11-10 11:11 UTC, div72 approved these changes
ACK 70a0e8172266900ce508730442d7c3ec4c103753, formatting is a bit unusual in a few lines but I am not even sure if it's nit-worthy.

> I thought it was a good idea for me to fix this, since I essentially broke it when I refactored stuff in here a while back. :)

No objections to less work. =P

2021-11-10 12:07 UTC, merged