lint: Fix misc typos
gridcoin-community/Gridcoin-Research pull request #2472
Opened 2022-03-22 19:08 UTC by barton2526

Found with codespell

2022-03-23 02:15 UTC, iFoggz requested changes

2022-03-23 02:15 UTC, iFoggz commented on src/rpc/blockchain.cpp
> +            throw runtime_error("Outsanding MRC request already present in the mempool for CPID.");
Outsanding? Outstanding was correct

2022-03-23 03:30 UTC, barton2526 commented on src/rpc/blockchain.cpp
> +            throw runtime_error("Outsanding MRC request already present in the mempool for CPID.");
fixed

2022-03-24 15:20 UTC, jamescowens approved these changes

2022-03-24 15:21 UTC, merged