gui: Fix wallet overview displaying lower-case poll name
gridcoin-community/Gridcoin-Research pull request #2640
Opened 2023-02-23 01:43 UTC by delta1513

Fixes #2638

Basically just added `m_title` as a data member to the `PollReference` object and copied the original poll name into there.

This preserves the lower-case poll name that is used for mapping to poll references but allows us to access a different member for the original name.

2023-02-28 22:03 UTC, jamescowens requested changes
Concept ACK.

You need to remove the if statement that conditions the to_lower at registry.cpp:1074 in DeletePoll, otherwise the delete will fail for contract version 2+ with your changes, because poll_title now remains in the original case, where the map key is lower case.

void PollRegistry::DeletePoll(const ContractContext& ctx) EXCLUSIVE_LOCKS_REQUIRED(cs_main, PollRegistry::cs_poll_registry)
{
    const auto payload = ctx->SharePayloadAs<PollPayload>();

    if (ctx->m_version >= 2) {
        m_polls.erase(payload->m_poll.m_title);
    } else {
        m_polls.erase(boost::to_lower_copy(payload->m_poll.m_title));
    }

    m_polls_by_txid.erase(ctx.m_tx.GetHash());
    m_latest_poll = nullptr;

    LogPrint(BCLog::LogFlags::VOTE, "INFO: %s: Deleted poll %s to the registry, m_polls.size() = %u.",
             __func__,
             payload->m_poll.m_title,
             m_polls.size());

}

2023-03-05 23:48 UTC, delta1513 commented
Got it, will work on this today!

2023-03-06 01:55 UTC, delta1513 commented
Would also like to point out that I removed the `boost::to_lower_copy` call in favour of `ToLower` like you mentioned in #2638 , should this become its own issue to remove all calls to this?

2023-03-12 03:06 UTC, jamescowens approved these changes
ACK.

2023-03-12 03:06 UTC, merged