Resize Header Column with Additional Text
gridcoin-community/Gridcoin-Research pull request #2683
Opened 2023-04-26 05:26 UTC by PrestackI

Problem:
The column for "Avg. Credit" in the Researcher Configuration under the Projects Tab is not wide enough to accommodate 1 million+ average credit amounts without showing them in scientific notation. The column is not resizable.

Observations:
It appears that the column width is dictated by the longest field text string or header text length within the column.  There are 2 exceptions:
- The integer "Avg. Credit" column that is showing a scientific notation instead of resizing to be shown in the standard form.
- The text "CPID" column that automatically resizes when you increase/decrease the width of the overall window.

Solution:
My solution is to add the text "Recent " to the text for the "Avg. Credit" header to accommodate larger numbers in their standard form. This should be sufficient to accommodate the largest RAC in the standard form.

Justification:
I believe this to the easiest and safest way to increase the field length to show larger numbers in their standard form without refactoring the table.  It will also bring congruence between the terminology used by BOINC and the Gridcoin Wallet.

2023-04-27 01:03 UTC, jamescowens commented
Might work. Have you tested it to see how it looks?

2023-04-27 02:07 UTC, PrestackI commented
I have not yet. Not exactly sure how to test it for Windows from scratch.

The instructions provided below appear to mention that is needs to be included in the testnet branch?
https://gridcoin.us/wiki/testnet.html

Any other suggestions?

2023-04-27 02:21 UTC, jamescowens commented
Do you know how to do a Windows build? You build from your branch. This build should be run on testnet.Sent from my iPhoneOn Apr 26, 2023, at 10:07 PM, PrestackI ***@***.***> wrote:﻿
I have not yet. Not exactly sure how to test it for Windows from scratch.
The instructions provided below appear to mention that is needs to be included in the testnet branch?
https://gridcoin.us/wiki/testnet.html
Any other suggestions?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-04-27 16:07 UTC, jamescowens commented
I tested this. You also need to change the projecttablemodel.cpp:
```
QVariant ProjectTableModel::data(const QModelIndex &index, int role) const
{
    if (!index.isValid()) {
        return QVariant();
    }

    const ProjectRow* row = static_cast<const ProjectRow*>(index.internalPointer());

    switch (role) {
        case Qt::DisplayRole:
            switch (index.column()) {
                case Name:
                    return row->m_name;
                case Eligible:
                    if (!row->m_error.isEmpty()) {
                        return row->m_error;
                    }
                    break;
                case GDPRControls:
                    if (row->m_gdpr_controls) {
                        return *row->m_gdpr_controls;
                    }
                    break;
                case Cpid:
                    return row->m_cpid;
                case Magnitude:
                    return row->m_magnitude;
                case RecentAverageCredit:
                    return QString::number(row->m_rac, 'f', 0);
            }
            break;
```
In particular in the case RecentAverageCredit, you need to change return row-m_rac to be QString::number(row->m_rac, 'f', 0).

2023-04-27 16:08 UTC, jamescowens requested changes
See my earlier comment.

2023-04-27 18:35 UTC, PrestackI commented
Added. 

Do I need to #include <QString>? Or is it taken care of with #include <QIcon?

2023-04-27 19:34 UTC, jamescowens commented
You don't

2023-04-28 01:42 UTC, jamescowens approved these changes
tACK

2023-04-28 01:42 UTC, merged