build: add Flatpak manifest file
gridcoin-community/Gridcoin-Research pull request #2724
Opened 2023-12-11 22:00 UTC by ikolomiko

I've created an initial Flatpak manifest file and a script to create a local Flatpak bundle. The permissions are pretty much bare-bones at this point. Since the manifest doesn't give read/write permissions for the `$HOME` directory, the application fails to start after the initial setup done by the wizard. There are 3 ways to overcome this issue:

1. Using a wrapper for setting the `datadir` to some predefined and sandboxed directory, just like [how Bitcoin-Core handles this issue](https://github.com/flathub/org.bitcoincore.bitcoin-qt/blob/master/install_wrappers.sh). This solution is pretty seamless and secure. However, it [restricts the user from choosing another directory](https://github.com/bitcoin/bitcoin/issues/24612), and feels like a dirty hack.
2. Letting the application access the `$HOME` directory. This approach requires the least effort. However, it violates the sandboxing Flatpak provides, and might cause conflicts if there's also a native version of Gridcoin installed besides the Flatpak version.
3. Using [the XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for the default location of `datadir`, instead of using the `~/.GridcoinResearch` directory. Following the XDG specifications is considered the best practice on Linux in general, both for Flatpak applications and for other package managers. However, this would require some modification in the codebase.

2023-12-11 22:13 UTC, jamescowens commented
Actually, IIRC correctly, we already have code in the app handling the special Flatpack data directory scenario for BOINC in boinc.cpp, but not for the main data directory. This deserves some discussion. I favor option 3.

We have an existing issue that is the inverse of choice 2, which is here.... https://github.com/gridcoin-community/Gridcoin-Research/issues/2650. The issue is that if both the native and flatpack BOINC are installed, the Gridcoin app defaults to the native version of BOINC.

Since we need to straighten out flatpack handling anyway, I strongly advocate choice 3.

We should have some discussion here about what that would look like.

2024-02-05 00:19 UTC, div72 requested changes
I'm all for following the XDG specification but Flatpak's default `XDG_*_HOME` variables are set to application specific `~/.var/app/us.gridcoin.Gridcoin-Research/...` which means a native installation and a Flatpak installation would have differing data directories. Flatpak advocates this but I'm not exactly sold on that. I think having a unified datadir is better UX overall.

P.S. @ikolomiko Are there any guidelines on publishing to the FlatHub? Like for example if we allow accessing `$HOME` would that disqualify the app from getting published?

2024-02-05 00:19 UTC, div72 commented on contrib/build-flatpak.sh
> +echo $repo_root
```suggestion
echo "$repo_root"
```
nit (shellcheck warn)

2024-02-05 00:19 UTC, div72 commented on contrib/build-flatpak.sh
> +repo_root="$(realpath $(dirname "$0")/..)"
```suggestion
repo_root="$(realpath "$(dirname "$0")/..")"
```
nit (shellcheck warn)

2024-02-05 00:19 UTC, div72 commented on contrib/build-flatpak.sh
> +
A small documentation on how to install the requirements(SDK, Platform), where the final build artifacts are and how to install it would be nice.

2024-02-05 00:19 UTC, div72 commented on contrib/flatpak-manifest.json
> +            ]
```suggestion
            "sources": [
                {
                    "type": "dir",
                    "path": ".."
                },
                {
                    "type": "shell",
                    "commands": ["./autogen.sh"]
                },
            ]
```
Getting: `bwrap: execvp ./configure: No such file or directory`

2024-02-05 21:40 UTC, ikolomiko commented
@div72 A general guideline can be found [here](https://docs.flathub.org/docs/for-app-authors/submission/). About the filesystem access for unified config data, there's [a special section in the Flathub requirements guide](https://docs.flathub.org/docs/for-app-authors/requirements/#filesystem-access) which strictly discourages that. While I'm not sure if it disqualifies the app from getting published on Flathub, it certainly is not the expected behavior of a Flatpak app.

2024-02-07 03:37 UTC, jamescowens commented
I think we need to live with the XDG spec. Do we need to modify the existing FlatPack handling code?

2024-02-07 03:38 UTC, jamescowens commented
The linter is barking again.... :)

2024-02-07 17:06 UTC, ikolomiko commented
Apparently the web editor of GitHub [inserts CRLF](https://github.com/orgs/community/discussions/84731) line endings to commit messages, causing the linter to go crazy, lol. Gotta rewrite the commit messages locally.

2024-02-08 14:36 UTC, jamescowens commented
That is crazy that the Github editor is following the Windows line ending standard...

2024-02-09 19:38 UTC, ikolomiko commented
Made a bunch of additions to the manifest for some permissions. AFAICT, the only missing piece is setting the default value of `datadir` to one of the XDG base directories. Possible candidates are `XDG_DATA_HOME`, `XDG_CONFIG_HOME` and `XDG_STATE_HOME`. Any ideas on which to pick?

2024-04-19 21:07 UTC, CyberTailor commented
> Using a wrapper for setting the datadir to some predefined and sandboxed directory, just like how Bitcoin-Core handles this issue. This solution is pretty seamless and secure. However, it restricts the user from choosing another directory, and feels like a dirty hack.

Actually no. Flatpak permissions can be fine-tuned in the system settings if you use KDE and in third-party [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) application otherwise.

2024-04-19 21:11 UTC, CyberTailor commented
I'd also like to note that a [`.metainfo.xml`](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/) file is required in order to be listed in app stores.

2024-04-19 21:14 UTC, CyberTailor commented
> I'm all for following the XDG specification but Flatpak's default XDG_*_HOME variables are set to application specific ~/.var/app/us.gridcoin.Gridcoin-Research/... which means a native installation and a Flatpak installation would have differing data directories. Flatpak advocates this but I'm not exactly sold on that. I think having a unified datadir is better UX overall.

Users installing both their distro's package and the Flatpak are going to be confused anyway.

2026-02-28 03:48 UTC, jamescowens commented
This PR got too stale to repair. Sorry about that. The concept has been superceded by #2861, which also includes building a flatpack release artifact in CD.

2026-02-28 03:48 UTC, closed without merging