Cleaned up StakeMiner.
gridcoin-community/Gridcoin-Research pull request #490
Opened 2017-08-06 22:14 UTC by tomasbrod

* Removed dead code
* unused PoW functionality.
* Added miner status structure
* added miner status to getmininginfo rpc
* replaced getstakinginfio rpc with alias to getmininginfo
* Use MinerStatus in some GlobalStatus fields.

2017-08-08 08:57 UTC, denravonska commented on src/main.cpp
> -extern int64_t ComputeResearchAccrual(int64_t nTime, std::string cpid, std::string operation, CBlockIndex* pindexLast, bool bVerifyingBlock, int VerificationPhase, double& dAccrualAge, double& dMagni
Thank you! The more forward declarations we remove the better.

2017-08-08 09:02 UTC, denravonska commented on src/miner.h
> +    void Clear()
I prefer code in cpp files or we end up with main.h. Not a deal breaker for this PR though :)

2017-08-08 09:08 UTC, denravonska commented on src/rpcmining.cpp
>  Value submitblock(const Array& params, bool fHelp)
`submitblock` doesn't seem to do anything as `ProcessBlock` is commented out. I opt for removing it as well.

2017-08-08 09:08 UTC, denravonska commented
Tooooons of obsolete code removed. Gj!

2017-08-08 09:13 UTC, denravonska commented on src/miner.cpp
> -        ((uint32_t*)data)[i] = ByteReverse(((uint32_t*)pinput)[i]);
`ByteReverse` in util.h is now unused and can be removed as well.

2017-08-08 09:18 UTC, tomasbrod commented on src/miner.h
> +    void Clear()
The problem with code in header is that it is implicitly inlined. Which adds compile time and duplicates code in resulting binary.

2017-08-10 03:44 UTC, denravonska commented on src/qt/bitcoingui.cpp
> +	labelStakingIcon->setToolTip("Not staking; "+QString(ReasonNotStaking.c_str()));
Missing tr macro.

2017-08-10 03:45 UTC, denravonska requested changes
Couple of small changes in comments.

2017-08-10 18:18 UTC, merged