Tie superblock average magnitude requirements to V7, non-testnet blocks.
gridcoin-community/Gridcoin-Research pull request #520
Opened 2017-08-18 12:48 UTC by denravonska

We still need to remove the mag boost in the NN, perhaps at a certain date.

2017-08-18 17:34 UTC, tomasbrod requested changes
Please go over it once more.
Also GetSuperblockAvgMag does more than it seems to. Maybe move some of the checks from there to VerifySuperblock?

2017-08-18 17:34 UTC, tomasbrod commented on src/main.cpp
> +    }
**I** just assert(parent) 😄

2017-08-18 17:34 UTC, tomasbrod commented on src/main.cpp
> -        double avg_mag = 0;
Changing the indentation makes it hard to compare.

2017-08-18 17:34 UTC, tomasbrod commented on src/main.cpp
> +    if(!fTestNet && parent->nVersion < 8 && avg_mag < 10)
Why version condition is different on testnet and prod?
New version is enabled separately for prod and test, so that hides the difference.

2017-08-18 17:34 UTC, tomasbrod commented on src/main.cpp
> +        bPassed = false;
It is set to fase a few lines back, this wont do anything.

2017-08-18 17:41 UTC, denravonska commented on src/main.cpp
> +    }
Asserts are removed with NDEBUG :)

2017-08-18 17:44 UTC, denravonska commented on src/main.cpp
> +        bPassed = false;
Are you mixing it up with `out_avg`? (honestly I have looked up the difference at least 4 times now but still can't tell them apart).

2017-08-18 17:51 UTC, denravonska commented on src/main.cpp
> +    if(!fTestNet && parent->nVersion < 8 && avg_mag < 10)
Not sure to be honest. I was trying to retain the original behavior. What should we change this to?

2017-08-19 04:57 UTC, denravonska commented
Replaced by #522.

2017-08-19 04:57 UTC, closed without merging